sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 13
before_install:
  - npm i -g npm@^6.14.5
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-releases